### ISSUE TITLE
Uncatched Error when Docker engine restarts

### ISSUE THREAD

**Issue by megastef** [mcollina/docker-loghose#15]
Hi,

since Docker 1.11 containers keep running when docker engine restarts. I think the error handling is not correct as I see uncaught errors in Sematext Docker Agent as well as in docker-loghose CLI tool. At least for Sematext Docker Agent I know it registers for error events and re-connects, but this seems to be broken. 

``````
docker-loghose 
{"v":0,"id":"f30a00a65527","image":"redis","name":"compassionate_goldberg","time":1467068375718,"line":"                _._                                                  \n           _.-``__ ''-._                                             \n      _.-``    `.  `_.  ''-._           Redis 3.2.1 (00000000/0) 64 bit\n  .-`` .-```.  ```\\/    _.,_ ''-._                                   \n (    '      ,       .-`  | `,    )     Running in standalone mode\n |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379\n |    `-._   `._    /     _.-'    |     PID: 1\n  `-._    `-._  `-./  _.-'    _.-'                                   \n |`-._`-._    `-.__.-'    _.-'_.-'|                                  \n |    `-._`-._        _.-'_.-'    |           http://redis.io        \n  `-._    `-._`-.__.-'_.-'    _.-'                                   \n |`-._`-._    `-.__.-'    _.-'_.-'|                                  \n |    `-._`-._        _.-'_.-'    |                                  \n  `-._    `-._`-.__.-'_.-'    _.-'                                   \n      `-._    `-.__.-'    _.-'                                       \n          `-._        _.-'                                           \n              `-.__.-'                                               \n"}
{"v":0,"id":"f30a00a65527","image":"redis","name":"compassionate_goldberg","time":1467068375734,"line":"1:M 27 Jun 22:59:35.716 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.\n1:M 27 Jun 22:59:35.733 # Server started, Redis version 3.2.1\n1:M 27 Jun 22:59:35.733 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.\n1:M 27 Jun 22:59:35.733 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled."}
{"v":0,"id":"f30a00a65527","image":"redis","name":"compassionate_goldberg","time":1467068375751,"line":"1:M 27 Jun 22:59:35.733 * The server is now ready to accept connections on port 6379"}
{"v":0,"id":"f30a00a65527","image":"redis","name":"compassionate_goldberg","time":1467068386201,"line":"1:signal-handler (1467068386) Received SIGTERM scheduling shutdown..."}
{"v":0,"id":"f30a00a65527","image":"redis","name":"compassionate_goldberg","time":1467068386257,"line":"1:M 27 Jun 22:59:46.255 # User requested shutdown...\n1:M 27 Jun 22:59:46.255 # Redis is now ready to exit, bye bye..."}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: (HTTP code 502) unexpected - Bad response from Docker engine

    at /usr/local/lib/node_modules/docker-loghose/node_modules/docker-modem/lib/modem.js:229:17
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/docker-loghose/node_modules/docker-modem/lib/modem.js:256:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
``````

How to reproduce? Start docker-loghose and restart Docker daemon / containerd.

**Comment by mcollina** [comment]
PR?

**Comment by mcollina** [comment]
This should be already fixed, in case reopen.
